#!/usr/bin/env python3

import os
import sys
from sys import argv

# anon-hotspot.py must be run as root!
script = argv

def root_check():
    if not os.geteuid() == 0:
        sys.exit(f"Must be run as root, i.e: \"sudo {script}\" to run as root.")

root_check()

def install_function():
    os.system("docker run -it ubuntu bash")

def start():
    sep = "-" * 15
    min_sep = "-" * 3
    print(sep, "anon-hotspot: Debian Linux (Tor) Hotspot " + sep)
    print("\nTool usage, i.e:")
    print("anon-hotspot tor-hotspot")
    print("\n" + min_sep + " available options " + min_sep + "\n")
    print("configuration:")
    print("- tor-hotspot (configure Tor WiFi hotspot)")
    print("- hotspot (configure WiFi hotspot)")
    print("- tor (configure Tor for existing Wifi hotspot)")
    print("- cred (change Tor/WiFi Hotspot ssid/passphrase)")
    print("- remove (remove Tor/Wifi Hotspot & revert to original settings)")

    print("\noperations:")
    print("- start (start Tor/WiFi hotspot)")
    print("- stop (stop Tor/WiFi hotspot)")
    choice = input(f"{script}> ")

    if choice == "left":
        bear_room()
    elif choice == "right":
        cthulhu_room()
    else:
        dead("You stumble around the room until you starve")

start()
